//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoForm.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 #软件配置
        ///APP_StartPosition=1  //启动位置：0-系统默认，1-屏幕中央，2-自动位置
        ///APP_BorderStyle=1  //边框样式：0-可调整，1-不可以调整
        ///APP_Size=480,360  //图像大小：宽,高   ，最小是480,360
        ///#海康配置
        ///HK_Channel=1    //设备通道
        ///HK_StreamType=1    //码流类型：0-主码流，1-子码流，2-码流3，3-码流4，以此类推
        ///HK_LinkMode=4    //连接方式：0- TCP方式，1- UDP方式，2- 多播方式，3- RTP方式，4-RTP/RTSP，5-RSTP/HTTP 
        ///#宇视配置
        ///UV_Channel=1    //通道号
        ///UV_StreamType=1    //0主码流，1子码流
        ///UV_LinkMode=1  //连接方式：0-UDP方式，1-TCP方式 的本地化字符串。
        /// </summary>
        internal static string conf_ini {
            get {
                return ResourceManager.GetString("conf_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] hk_dll {
            get {
                object obj = ResourceManager.GetObject("hk_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 # VideoForm 视频预览
        ///## 本地视频文件
        ///VideoForm.exe &quot;file://c:/video.mp4&quot;
        ///## 海康视频流协议
        ///VideoForm.exe &quot;hikvision://admin:pwd@192.168.1.64:8000&quot;
        ///## 宇视视频流协议
        ///VideoForm.exe &quot;uniview://admin:pwd@192.168.1.64:80&quot;
        ///## 通用视频协议 (rtmp/rtsp/http)
        ///VideoForm.exe &quot;rtmp://192.168.1.64/live/stream&quot;
        ///VideoForm.exe &quot;rtsp://192.168.1.64:554/live/stream&quot;
        ///VideoForm.exe &quot;http://192.168.1.64:8000/stream.m3u8&quot;
        ///VideoForm.exe &quot;http://192.168.1.64:8000/mjpg/video.mjpg&quot; 的本地化字符串。
        /// </summary>
        internal static string readme {
            get {
                return ResourceManager.GetString("readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] uniview_dll {
            get {
                object obj = ResourceManager.GetObject("uniview_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
